### ISSUE TITLE
Create User database models

### ISSUE THREAD

**Issue by Duveshka** [laska-sl/arcadia-parties#5]
Model fields: 
ID
Login
Password
FirstName
LastName
MiddleName
AccessRights
BirthDate
HireDate

**Comment by sponkrashin** [comment]
No need to have password, because you don't manage users in your application, just request them from somewhere. So you need to store user identity (for windows authentication it is DOMAIN\username), first/last name and dates. Access rights should be stored in another table, even in two tables - Role and UserRole.
